// build-corpus.js: the one-command full-corpus icon build.
//
// Reads the enumerated corpus lists (from enumerate-corpus.js),
// expands every SIDC to all four frame bases (full-frame icons carry
// per-base geometry, and codegen's body comparison collapses the
// universal ones), then runs the standard pipeline: extract, keys,
// codegen. Each stage is timed.
//
// Usage, from tools/extract, after enumerate-corpus.js:
//   node build-corpus.js
//
// Inputs:  out/corpus-delta.txt, out/corpus-charlie.txt
// Outputs: out/corpus-all.txt, out/corpus-icons.json,
//          out/corpus-keys.tsv, and the sharded generated Swift.

import { readFileSync, writeFileSync } from "node:fs";
import { execSync } from "node:child_process";

function readList(path) {
  return readFileSync(path, "utf8")
    .split("\n")
    .map((line) => line.trim())
    .filter((line) => line.length > 0 && !line.startsWith("#"));
}

// Frame-base identity expansion. The enumerated lists are friend;
// hostile, neutral, and unknown complete the four bases.
function expandDelta(sidc) {
  return ["3", "6", "4", "1"].map(
    (identity) => sidc.slice(0, 3) + identity + sidc.slice(4)
  );
}

function expandCharlie(sidc) {
  return ["F", "H", "N", "U"].map(
    (identity) => sidc.slice(0, 1) + identity + sidc.slice(2)
  );
}

function timed(label, fn) {
  const startedAt = Date.now();
  const result = fn();
  console.log(`[${label}] ${((Date.now() - startedAt) / 1000).toFixed(1)}s`);
  return result;
}

const delta = readList("out/corpus-delta.txt");
const charlie = readList("out/corpus-charlie.txt");
console.log(`Corpus: ${delta.length} delta + ${charlie.length} charlie icons`);

const all = [
  "# Full corpus, all four frame bases, generated by build-corpus.js.",
  ...delta.flatMap(expandDelta),
  ...charlie.flatMap(expandCharlie),
];
writeFileSync("out/corpus-all.txt", all.join("\n") + "\n");
console.log(`Expanded to ${all.length - 1} SIDCs (out/corpus-all.txt)`);

timed("extract", () =>
  execSync(
    "node extract.js --sidcs out/corpus-all.txt --icon-extract --out out/corpus-icons.json",
    { stdio: "inherit" }
  )
);

timed("keys", () => {
  const tsv = execSync(
    "swift run ensign-catalog keys tools/extract/out/corpus-all.txt",
    { cwd: "../..", encoding: "utf8", maxBuffer: 256 * 1024 * 1024 }
  );
  writeFileSync("out/corpus-keys.tsv", tsv);
});

timed("codegen", () =>
  execSync(
    "node codegen.js --icons out/corpus-icons.json --keys out/corpus-keys.tsv",
    { stdio: "inherit" }
  )
);

console.log("\nCorpus build complete; now: cd ../.. && swift build && swift test");